import bcrypt from "bcryptjs";
import { connectDB } from "@/lib/mongodb";
import { User } from "@/models/User";
import { Product } from "@/models/Product";
import { Coupon } from "@/models/Coupon";
import { Order } from "@/models/Order";
import { Review } from "@/models/Review";

const generateSlug = (name: string): string => {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim();
};

const seedData = {
  users: [
    {
      name: "Admin User",
      email: "admin@bekaarcool.com",
      password: bcrypt.hashSync("admin123", 12),
      role: "admin",
      isVerified: true,
      isActive: true,
    },
    {
      name: "John Doe",
      email: "john@example.com",
      password: bcrypt.hashSync("password123", 12),
      role: "customer",
      isVerified: true,
      isActive: true,
      phone: "+91 98765 43210",
      addresses: [
        {
          type: "home",
          name: "John Doe",
          phone: "+91 98765 43210",
          address: "123 Main Street, Apartment 4B",
          city: "Mumbai",
          state: "Maharashtra",
          pincode: "400001",
          isDefault: true,
        },
      ],
    },
    {
      name: "Jane Smith",
      email: "jane@example.com",
      password: bcrypt.hashSync("password123", 12),
      role: "seller",
      isVerified: true,
      isActive: true,
      phone: "+91 98765 43211",
    },
  ],
  products: [
    // Fashion - T-Shirts
    {
      name: "Custom Cotton T-Shirt Black",
      description: "Premium 100% cotton t-shirt perfect for custom printing. Soft, comfortable, and durable.",
      price: 599,
      originalPrice: 799,
      category: "Fashion",
      subcategory: "T-Shirts",
      brand: "BeKaarCool",
      stock: 150,
      images: ["/placeholder.jpg"],
      customizable: true,
      isActive: true,
      isFeatured: true,
      rating: 4.5,
      reviewCount: 89,
    },
    {
      name: "Custom Cotton T-Shirt White",
      description: "Classic white cotton t-shirt ideal for custom designs and everyday wear.",
      price: 599,
      originalPrice: 799,
      category: "Fashion",
      subcategory: "T-Shirts",
      brand: "BeKaarCool",
      stock: 200,
      images: ["/placeholder.jpg"],
      customizable: true,
      isActive: true,
      isFeatured: true,
      rating: 4.6,
      reviewCount: 124,
    },
    {
      name: "Custom Cotton T-Shirt Navy Blue",
      description: "Navy blue cotton t-shirt with premium quality fabric for custom printing.",
      price: 599,
      originalPrice: 799,
      category: "Fashion",
      subcategory: "T-Shirts",
      brand: "BeKaarCool",
      stock: 120,
      images: ["/placeholder.jpg"],
      customizable: true,
      isActive: true,
      rating: 4.4,
      reviewCount: 67,
    },
    {
      name: "Custom Cotton T-Shirt Red",
      description: "Vibrant red cotton t-shirt perfect for bold custom designs.",
      price: 599,
      originalPrice: 799,
      category: "Fashion",
      subcategory: "T-Shirts",
      brand: "BeKaarCool",
      stock: 100,
      images: ["/placeholder.jpg"],
      customizable: true,
      isActive: true,
      rating: 4.3,
      reviewCount: 45,
    },
    {
      name: "Custom Cotton T-Shirt Gray",
      description: "Stylish gray cotton t-shirt with excellent print quality and comfort.",
      price: 599,
      originalPrice: 799,
      category: "Fashion",
      subcategory: "T-Shirts",
      brand: "BeKaarCool",
      stock: 110,
      images: ["/placeholder.jpg"],
      customizable: true,
      isActive: true,
      rating: 4.5,
      reviewCount: 78,
    },
    // Fashion - Hoodies
    {
      name: "Premium Custom Hoodie Black",
      description: "Comfortable black hoodie with custom print options, perfect for winter wear.",
      price: 1299,
      originalPrice: 1599,
      category: "Fashion",
      subcategory: "Hoodies",
      brand: "BeKaarCool",
      stock: 75,
      images: ["/placeholder.jpg"],
      customizable: true,
      isActive: true,
      isFeatured: true,
      rating: 4.7,
      reviewCount: 156,
    },
    {
      name: "Premium Custom Hoodie Gray",
      description: "Cozy gray hoodie made from premium materials, ideal for custom designs.",
      price: 1299,
      originalPrice: 1599,
      category: "Fashion",
      subcategory: "Hoodies",
      brand: "BeKaarCool",
      stock: 60,
      images: ["/placeholder.jpg"],
      customizable: true,
      isActive: true,
      rating: 4.6,
      reviewCount: 98,
    },
    {
      name: "Premium Custom Hoodie Navy",
      description: "Navy blue hoodie with excellent print quality and comfortable fit.",
      price: 1299,
      originalPrice: 1599,
      category: "Fashion",
      subcategory: "Hoodies",
      brand: "BeKaarCool",
      stock: 50,
      images: ["/placeholder.jpg"],
      customizable: true,
      isActive: true,
      rating: 4.5,
      reviewCount: 87,
    },
    // Fashion - Polo Shirts
    {
      name: "Custom Polo Shirt White",
      description: "Classic white polo shirt perfect for corporate branding and custom logos.",
      price: 899,
      originalPrice: 1199,
      category: "Fashion",
      subcategory: "Polo Shirts",
      brand: "BeKaarCool",
      stock: 80,
      images: ["/placeholder.jpg"],
      customizable: true,
      isActive: true,
      rating: 4.4,
      reviewCount: 65,
    },
    {
      name: "Custom Polo Shirt Black",
      description: "Elegant black polo shirt with premium fabric quality for professional use.",
      price: 899,
      originalPrice: 1199,
      category: "Fashion",
      subcategory: "Polo Shirts",
      brand: "BeKaarCool",
      stock: 70,
      images: ["/placeholder.jpg"],
      customizable: true,
      isActive: true,
      rating: 4.3,
      reviewCount: 54,
    },
    // Fashion - Tank Tops
    {
      name: "Custom Tank Top Black",
      description: "Comfortable black tank top perfect for gym wear and custom designs.",
      price: 399,
      originalPrice: 599,
      category: "Fashion",
      subcategory: "Tank Tops",
      brand: "BeKaarCool",
      stock: 90,
      images: ["/placeholder.jpg"],
      customizable: true,
      isActive: true,
      rating: 4.2,
      reviewCount: 43,
    },
    {
      name: "Custom Tank Top White",
      description: "Classic white tank top with excellent breathability and print quality.",
      price: 399,
      originalPrice: 599,
      category: "Fashion",
      subcategory: "Tank Tops",
      brand: "BeKaarCool",
      stock: 85,
      images: ["/placeholder.jpg"],
      customizable: true,
      isActive: true,
      rating: 4.1,
      reviewCount: 38,
    },
    // Fashion - Sweatshirts
    {
      name: "Custom Sweatshirt Gray",
      description: "Warm and comfortable gray sweatshirt perfect for custom printing.",
      price: 1099,
      originalPrice: 1399,
      category: "Fashion",
      subcategory: "Sweatshirts",
      brand: "BeKaarCool",
      stock: 65,
      images: ["/placeholder.jpg"],
      customizable: true,
      isActive: true,
      rating: 4.5,
      reviewCount: 72,
    },
    {
      name: "Custom Sweatshirt Black",
      description: "Classic black sweatshirt with premium quality fabric and excellent durability.",
      price: 1099,
      originalPrice: 1399,
      category: "Fashion",
      subcategory: "Sweatshirts",
      brand: "BeKaarCool",
      stock: 55,
      images: ["/placeholder.jpg"],
      customizable: true,
      isActive: true,
      rating: 4.4,
      reviewCount: 61,
    },
    // Electronics
    {
      name: "Wireless Bluetooth Headphones Pro",
      description: "Premium wireless headphones with active noise cancellation and 30-hour battery life.",
      price: 2999,
      originalPrice: 3999,
      category: "Electronics",
      subcategory: "Audio",
      brand: "TechSound",
      stock: 50,
      images: ["/placeholder.jpg"],
      isActive: true,
      isFeatured: true,
      rating: 4.6,
      reviewCount: 234,
    },
    {
      name: "Smartphone Case Clear Protection",
      description: "Crystal clear protective case with military-grade drop protection for all smartphones.",
      price: 299,
      originalPrice: 499,
      category: "Electronics",
      subcategory: "Accessories",
      brand: "ProtectPro",
      stock: 200,
      images: ["/placeholder.jpg"],
      isActive: true,
      rating: 4.2,
      reviewCount: 167,
    },
    {
      name: "Wireless Charging Pad Fast",
      description: "Fast wireless charging pad compatible with all Qi-enabled devices.",
      price: 1299,
      originalPrice: 1699,
      category: "Electronics",
      subcategory: "Accessories",
      brand: "ChargeTech",
      stock: 75,
      images: ["/placeholder.jpg"],
      isActive: true,
      rating: 4.3,
      reviewCount: 89,
    },
    {
      name: "Bluetooth Speaker Portable",
      description: "Compact portable Bluetooth speaker with powerful bass and 12-hour battery.",
      price: 1999,
      originalPrice: 2499,
      category: "Electronics",
      subcategory: "Audio",
      brand: "SoundWave",
      stock: 60,
      images: ["/placeholder.jpg"],
      isActive: true,
      rating: 4.4,
      reviewCount: 145,
    },
    {
      name: "USB Cable Type C Fast Charging",
      description: "High-quality Type-C cable with fast charging and data transfer capabilities.",
      price: 199,
      originalPrice: 299,
      category: "Electronics",
      subcategory: "Accessories",
      brand: "CablePro",
      stock: 300,
      images: ["/placeholder.jpg"],
      isActive: true,
      rating: 4.1,
      reviewCount: 78,
    },
    // Home & Kitchen
    {
      name: "Stainless Steel Water Bottle Insulated",
      description: "Premium insulated water bottle that keeps drinks cold for 24 hours and hot for 12 hours.",
      price: 899,
      originalPrice: 1199,
      category: "Home & Kitchen",
      subcategory: "Drinkware",
      brand: "HydroMax",
      stock: 120,
      images: ["/placeholder.jpg"],
      isActive: true,
      isFeatured: true,
      rating: 4.7,
      reviewCount: 203,
    },
    {
      name: "Coffee Mug Ceramic White",
      description: "Classic white ceramic coffee mug perfect for daily use and custom printing.",
      price: 299,
      originalPrice: 399,
      category: "Home & Kitchen",
      subcategory: "Drinkware",
      brand: "CeramicCraft",
      stock: 150,
      images: ["/placeholder.jpg"],
      customizable: true,
      isActive: true,
      rating: 4.3,
      reviewCount: 92,
    },
    {
      name: "Travel Mug Stainless Steel",
      description: "Leak-proof travel mug with double-wall insulation for hot and cold beverages.",
      price: 699,
      originalPrice: 899,
      category: "Home & Kitchen",
      subcategory: "Drinkware",
      brand: "TravelPro",
      stock: 100,
      images: ["/placeholder.jpg"],
      isActive: true,
      rating: 4.5,
      reviewCount: 134,
    },
    {
      name: "Kitchen Cutting Board Bamboo",
      description: "Eco-friendly bamboo cutting board with antimicrobial properties.",
      price: 799,
      originalPrice: 999,
      category: "Home & Kitchen",
      subcategory: "Kitchen Tools",
      brand: "EcoKitchen",
      stock: 80,
      images: ["/placeholder.jpg"],
      isActive: true,
      rating: 4.4,
      reviewCount: 67,
    },
    // Sports & Fitness
    {
      name: "Yoga Mat Premium Non Slip",
      description: "Premium non-slip yoga mat made from eco-friendly TPE material.",
      price: 1299,
      originalPrice: 1699,
      category: "Sports & Fitness",
      subcategory: "Yoga",
      brand: "ZenFit",
      stock: 70,
      images: ["/placeholder.jpg"],
      isActive: true,
      rating: 4.6,
      reviewCount: 156,
    },
    {
      name: "Resistance Bands Set Heavy Duty",
      description: "Complete set of heavy-duty resistance bands for full-body workouts.",
      price: 999,
      originalPrice: 1299,
      category: "Sports & Fitness",
      subcategory: "Exercise Equipment",
      brand: "FitPro",
      stock: 90,
      images: ["/placeholder.jpg"],
      isActive: true,
      rating: 4.3,
      reviewCount: 89,
    },
    {
      name: "Gym Water Bottle Large",
      description: "Large capacity gym water bottle with measurement markers and leak-proof design.",
      price: 599,
      originalPrice: 799,
      category: "Sports & Fitness",
      subcategory: "Accessories",
      brand: "GymGear",
      stock: 110,
      images: ["/placeholder.jpg"],
      isActive: true,
      rating: 4.2,
      reviewCount: 73,
    },
    // Accessories
    {
      name: "Custom Tote Bag Canvas",
      description: "Durable canvas tote bag perfect for custom printing and everyday use.",
      price: 499,
      originalPrice: 699,
      category: "Accessories",
      subcategory: "Bags",
      brand: "BeKaarCool",
      stock: 120,
      images: ["/placeholder.jpg"],
      customizable: true,
      isActive: true,
      rating: 4.4,
      reviewCount: 85,
    },
    {
      name: "Custom Baseball Cap Black",
      description: "Classic black baseball cap with adjustable strap, perfect for custom embroidery.",
      price: 699,
      originalPrice: 899,
      category: "Accessories",
      subcategory: "Caps",
      brand: "BeKaarCool",
      stock: 100,
      images: ["/placeholder.jpg"],
      customizable: true,
      isActive: true,
      rating: 4.3,
      reviewCount: 94,
    },
    {
      name: "Custom Backpack School",
      description: "Spacious school backpack with multiple compartments, ideal for custom branding.",
      price: 1499,
      originalPrice: 1899,
      category: "Accessories",
      subcategory: "Bags",
      brand: "BeKaarCool",
      stock: 60,
      images: ["/placeholder.jpg"],
      customizable: true,
      isActive: true,
      rating: 4.5,
      reviewCount: 112,
    },
    {
      name: "Custom Mouse Pad Gaming",
      description: "Large gaming mouse pad with smooth surface, perfect for custom designs.",
      price: 399,
      originalPrice: 599,
      category: "Accessories",
      subcategory: "Tech Accessories",
      brand: "BeKaarCool",
      stock: 150,
      images: ["/placeholder.jpg"],
      customizable: true,
      isActive: true,
      rating: 4.2,
      reviewCount: 67,
    },
    {
      name: "Custom Phone Stand Wooden",
      description: "Elegant wooden phone stand perfect for desk use and custom engraving.",
      price: 599,
      originalPrice: 799,
      category: "Accessories",
      subcategory: "Tech Accessories",
      brand: "WoodCraft",
      stock: 80,
      images: ["/placeholder.jpg"],
      customizable: true,
      isActive: true,
      rating: 4.4,
      reviewCount: 56,
    },
  ],
  coupons: [
    {
      code: "WELCOME20",
      description: "Welcome offer - 20% off on your first order",
      discountType: "percentage",
      discountValue: 20,
      maxDiscountAmount: 500,
      minOrderAmount: 999,
      usageLimit: 1000,
      usedCount: 45,
      validFrom: new Date("2024-01-01"),
      validTo: new Date("2024-12-31"),
      isActive: true,
    },
    {
      code: "SAVE100",
      description: "Flat ₹100 off on orders above ₹1999",
      discountType: "fixed",
      discountValue: 100,
      minOrderAmount: 1999,
      usageLimit: 500,
      usedCount: 23,
      validFrom: new Date("2024-01-01"),
      validTo: new Date("2024-06-30"),
      isActive: true,
    },
    {
      code: "FASHION15",
      description: "15% off on all fashion items",
      discountType: "percentage",
      discountValue: 15,
      maxDiscountAmount: 300,
      minOrderAmount: 799,
      usageLimit: 200,
      usedCount: 12,
      validFrom: new Date("2024-01-01"),
      validTo: new Date("2024-03-31"),
      isActive: true,
      applicableCategories: ["Fashion"],
    },
    {
      code: "ELECTRONICS10",
      description: "10% off on all electronics",
      discountType: "percentage",
      discountValue: 10,
      maxDiscountAmount: 1000,
      minOrderAmount: 1499,
      usageLimit: 300,
      usedCount: 34,
      validFrom: new Date("2024-01-01"),
      validTo: new Date("2024-04-30"),
      isActive: true,
      applicableCategories: ["Electronics"],
    },
    {
      code: "CUSTOM25",
      description: "25% off on all customizable products",
      discountType: "percentage",
      discountValue: 25,
      maxDiscountAmount: 750,
      minOrderAmount: 1299,
      usageLimit: 150,
      usedCount: 18,
      validFrom: new Date("2024-01-01"),
      validTo: new Date("2024-05-31"),
      isActive: true,
    },
  ],
};

async function seedDatabase() {
  try {
    await connectDB();

    console.log("Clearing existing data...");
    await User.deleteMany({});
    await Product.deleteMany({});
    await Coupon.deleteMany({});
    await Order.deleteMany({});
    await Review.deleteMany({});

    console.log("Creating users...");
    const users = await User.insertMany(seedData.users);
    const adminUser = users.find(u => u.role === "admin");
    const customerUser = users.find(u => u.role === "customer");
    const sellerUser = users.find(u => u.role === "seller");

    console.log("Creating products...");
    const productsWithDetails = seedData.products.map((product, index) => ({
      ...product,
      slug: generateSlug(product.name),
      sku: `BKC-${String(index + 1).padStart(3, '0')}`,
      seller: sellerUser._id,
      seoTitle: `${product.name} - Buy Online at BeKaarCool | Best ${product.category}`,
      seoDescription: product.description.length > 160 ? product.description.substring(0, 157) + '...' : product.description,
      seoKeywords: [
        ...product.name.toLowerCase().split(' '),
        product.category.toLowerCase(),
        product.brand.toLowerCase(),
        'buy online',
        'india',
        ...(product.customizable ? ['custom', 'personalized'] : [])
      ],
      tags: product.name.toLowerCase().split(' ').concat(product.category.toLowerCase().split(' ')),
      variations: product.customizable ? {
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        colors: product.name.includes('Black') ? ['Black'] : 
                product.name.includes('White') ? ['White'] :
                product.name.includes('Navy') ? ['Navy'] :
                product.name.includes('Red') ? ['Red'] :
                product.name.includes('Gray') ? ['Gray'] :
                ['Black', 'White', 'Navy', 'Red', 'Gray']
      } : undefined,
    }));
    const products = await Product.insertMany(productsWithDetails);

    console.log("Creating coupons...");
    await Coupon.insertMany(seedData.coupons);

    console.log("Creating sample orders...");
    const sampleOrders = [
      {
        orderNumber: `ORD-${Date.now()}-001`,
        user: customerUser._id,
        customer: customerUser._id,
        items: [
          {
            product: products[0]._id,
            quantity: 2,
            price: 599,
            size: "M",
            color: "Black",
          },
        ],
        total: 1298,
        subtotal: 1198,
        shipping: 100,
        tax: 0,
        discount: 0,
        status: "delivered",
        paymentStatus: "paid",
        paymentMethod: "razorpay",
        paymentId: "pay_sample123",
        shippingAddress: {
          name: "John Doe",
          phone: "+91 98765 43210",
          address: "123 Main Street, Apartment 4B",
          city: "Mumbai",
          state: "Maharashtra",
          pincode: "400001",
          country: "India",
        },
        trackingNumber: "TRK001",
        estimatedDelivery: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
      },
      {
        orderNumber: `ORD-${Date.now()}-002`,
        user: customerUser._id,
        customer: customerUser._id,
        items: [
          {
            product: products[5]._id,
            quantity: 1,
            price: 1299,
            size: "L",
            color: "Black",
          },
        ],
        total: 1399,
        subtotal: 1299,
        shipping: 100,
        tax: 0,
        discount: 0,
        status: "confirmed",
        paymentStatus: "paid",
        paymentMethod: "cod",
        shippingAddress: {
          name: "John Doe",
          phone: "+91 98765 43210",
          address: "123 Main Street, Apartment 4B",
          city: "Mumbai",
          state: "Maharashtra",
          pincode: "400001",
          country: "India",
        },
        estimatedDelivery: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      },
    ];

    await Order.insertMany(sampleOrders);

    console.log("Creating sample reviews...");
    const sampleReviews = products.slice(0, 10).map((product, index) => ({
      product: product._id,
      user: customerUser._id,
      rating: 4 + Math.random(),
      title: `Great ${product.name.split(' ')[0]}!`,
      comment: `Excellent quality and fast delivery. Very satisfied with this ${product.name.toLowerCase()}.`,
      isVerified: true,
      createdAt: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000),
    }));

    await Review.insertMany(sampleReviews);

    console.log("✅ Database seeded successfully!");
    console.log(`Created ${users.length} users`);
    console.log(`Created ${products.length} products`);
    console.log(`Created ${seedData.coupons.length} coupons`);
    console.log(`Created ${sampleOrders.length} orders`);
    console.log(`Created ${sampleReviews.length} reviews`);

  } catch (error) {
    console.error("❌ Error seeding database:", error);
  }
}

export default seedDatabase;

if (require.main === module) {
  seedDatabase().then(() => process.exit(0));
}